
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Zebra </title>
        <meta name="keywords" content="HTML5 Bootstrap 3 Admin Template UI Theme" />
        <meta name="description" content="AdminDesigns - SHARED ON THEMELOCK.COM">
        <meta name="author" content="AdminDesigns">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">


        <!-- Font CSS (Via CDN) -->
        <link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700'>
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700">

        <!-- Theme CSS -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/assets/skin/default_skin/css/theme.css">

        <!-- Admin Panels CSS -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/assets/admin-tools/admin-plugins/admin-panels/adminpanels.css">

        <!-- Admin Forms CSS -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/assets/admin-tools/admin-forms/css/admin-forms.css">

        <!-- Favicon -->
        <link rel="shortcut icon" href="<?php echo $this->basePath() ?>/assets/img/favicon1.ico">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/vendor/plugins/datepicker/css/bootstrap-datetimepicker.min.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/vendor/plugins/daterange/daterangepicker.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/vendor/plugins/colorpicker/css/bootstrap-colorpicker.min.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/vendor/plugins/tagmanager/tagmanager.css">
    </head>

    <body class="error-page alt sb-l-c sb-r-c">

        <!-- Start: Main -->
        <div id="main">



            <!-- Start: Sidebar -->


            <!-- Start: Content-Wrapper -->
            <section id="content_wrapper">





                <!-- Begin: Content -->
                <section id="content" class="pn animated fadeIn">

                    <div class="center-block mt50 mw800">
                        <h1 class="error-title"> ¡404! </h1>
                        <h2 class="error-subtitle">¡Pagina no Encontrada!</h2>
                    </div>

                    <a href="<?php echo $this->basePath()?>/application" id="return-arrow">
                        <i class="fa fa-arrow-left fa-3x text-primary"></i>
                        <span> Regresa
                            <br> Al Inicio </span>
                    </a>

                </section>
                <!-- End: Content -->

            </section>

        </div>
        <!-- End: Main -->

        <!-- BEGIN: PAGE SCRIPTS -->

        <!-- jQuery -->
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/vendor/jquery/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/vendor/jquery/jquery_ui/jquery-ui.min.js"></script>

        <!-- Bootstrap -->
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets/js/bootstrap/bootstrap.min.js"></script>

        <!-- Theme Javascript -->
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets/js/utility/utility.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets/js/main.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets/js/demo.js"></script>
        <script type="text/javascript">
            jQuery(document).ready(function () {

                "use strict";

                // Init Theme Core    
                Core.init();

                // Init Demo JS    
                Demo.init();


            });
        </script>
        <!-- END: PAGE SCRIPTS -->

    </body>
</html>