

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('application/default', array('controller' => 'index', 'action' => 'login')));
$form->prepare(); ?>
<!DOCTYPE html>
<html>

    <head>
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <title>AdminDesigns - A Responsive HTML5 Admin UI Framework</title>
        <meta name="keywords" content="HTML5 Bootstrap 3 Admin Template UI Theme" />
        <meta name="description" content="AdminDesigns - A Responsive HTML5 Admin UI Framework">
        <meta name="author" content="AdminDesigns">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Font CSS (Via CDN) -->
        <link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800'>
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Roboto:400,500,700,300">

        <!-- Theme CSS -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/assets/skin/default_skin/css/theme.css">

        <!-- Admin Forms CSS -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/assets/admin-tools/admin-forms/css/admin-forms.css">


        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
       <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
       <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
       <![endif]-->
    </head>

    <body class="external-page sb-l-c sb-r-c">

        <!-- Start: Main -->
        <div id="main" class="animated fadeIn">

            <!-- Start: Content-Wrapper -->
            <section id="content_wrapper">

                <!-- begin canvas animation bg -->
                <div id="canvas-wrapper">
                    <canvas id="demo-canvas"></canvas>
                </div>

                <!-- Begin: Content -->
                <section id="content">

                    <div class="admin-form theme-info" id="login1">

                        <div class="row mb15 table-layout">

                            <div class="col-xs-6 va-m pln">
                                <a href="dashboard.html" title="Return to Dashboard">
                                    <img src="<?php echo $this->basePath() ?>/assets/img/logos/logo.jpg" title="AdminDesigns Logo" class="img-responsive w250">
                                </a>
                            </div>

                            <div class="col-xs-6 text-right va-b pr5">
                                <div class="login-links">
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'registration', 'action' => 'forgotten-password')); ?>"><?php echo $this->translate('Forgotten Password'); ?></a>
                                    <span class="text-white"> | </span>
                                    <a href="<?php echo $this->url('application/default', array('controller' => 'registration', 'action' => 'index')); ?>"><?php echo $this->translate('Register'); ?></a> |  
                                </div>

                            </div>

                        </div>

                        <div class="panel panel-info mt10 br-n">


                            <!-- end .form-header section -->
                            <?php echo $this->form()->openTag($form); ?>
                                <div class="panel-body bg-light p30">
                                    <div class="row">
                                        <div class="col-sm-offset-3 col-sm-7 pr30">


                                            <div class="section">
                                                <label for="username" class="field-label text-muted fs18 mb10">Username</label>
                                                <label for="username" class="field prepend-icon">
                                                    <?php echo $this->formRow($form->get('usr_name')); ?>
                                                    <label for="username" class="field-icon"><i class="fa fa-user"></i>
                                                    </label>
                                                </label>
                                            </div>
                                            <!-- end section -->

                                            <div class="section">
                                                <label for="username" class="field-label text-muted fs18 mb10">Password</label>
                                                <label for="password" class="field prepend-icon">
                                                    <?php echo $this->formRow($form->get('usr_password')); ?>
                                                    <label for="password" class="field-icon"><i class="fa fa-lock"></i>
                                                    </label>
                                                </label>
                                            </div>
                                            <!-- end section -->

                                        </div>
                                    </div>
                                </div>
                                <!-- end .form-body section -->
                                <div class="panel-footer clearfix p10 ph15">
                                    <?php echo $this->formSubmit($form->get('submit')); ?>
                                    <label class="switch block switch-primary pull-left input-align mt10">
                                        <?php echo $this->formCheckbox($form->get('rememberme')); ?>
                                        <label for="remember" data-on="YES" data-off="NO"></label>
                                        <span>Remember me</span>
                                    </label>
                                </div>
                                <!-- end .form-footer section -->
                           <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>

                </section>
                <!-- End: Content -->

            </section>
            <!-- End: Content-Wrapper -->

        </div>
        <!-- End: Main -->

        <!-- BEGIN: PAGE SCRIPTS -->

        <!-- jQuery -->
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets/js/jquery/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets/js/jquery/jquery_ui/jquery-ui.min.js"></script>

        <!-- Bootstrap -->
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets/js/bootstrap/bootstrap.min.js"></script>

        <!-- Page Plugins -->
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets/js/pages/login/EasePack.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets/js/pages/login/rAF.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets/js/pages/login/TweenLite.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/assets/js/pages/login/login.js"></script>


        <!-- Page Javascript -->
        <script type="text/javascript">
            jQuery(document).ready(function () {

                "use strict";

                // Init Theme Core      
                Core.init();

                // Init Demo JS
                Demo.init();

                // Init CanvasBG and pass target starting location
                CanvasBG.init({
                    Loc: {
                        x: window.innerWidth / 2,
                        y: window.innerHeight / 3.3
                    },
                });


            });
        </script>

        <!-- END: PAGE SCRIPTS -->

    </body>


</html>

